### ISSUE TITLE
Unsupported engine

### ISSUE THREAD

**Issue by fluxxus** [boycce/cherry#12]
Hey, I get the above error when installing. Node v18 required, I have v20.8.1. 

Can you make it more flexible? :) I prefer to avoid `--legacy-peer-deps` or `-force`.

P.S. 
Your little library is exactly what I needed, super nice base that I can easily extend/customise.

**Comment by boycce** [comment]
Hi @fluxxus, updated to `"node": ">=18"`

Thanks, I'm glad you like it 😊
